[package]
name = "kani-comix"
version = "0.1.0"
edition = "2024"

[lints.clippy]
unwrap_used = { level = "deny", priority = 1 }

[package.metadata]
id = "comix"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
kani-shared = { git = "https://github.com/ArloB/kani", branch = "develop", features = ["builder"] }
