#[cfg(not(target_family = "wasm"))]
compile_error!(
    "kani-extensions/* are WASM-only -- build with `cargo run -p kani-cli -- build <name>`. \
     If a tool triggered this, it is using --workspace (or defaulting to it); scope it to \
     default-members instead -- clippy/nextest omit the flag, cargo-dist needs precise-builds."
);

// @generated by kani-cli from mangapill-gen.yaml — edit freely, but regenerate with `kani-cli generate` to reset.

use kani_shared::bindings::exports::kani::extension::manga_provider::Guest;
use kani_shared::host_abi::{extract_raw, HttpRequest};
use kani_shared::{
    bindings, ext_version, filter_list, to_shared_filters, types::ActiveFilter, wit_types,
    ExtensionMetadata, ExtensionResult, FilterState, MangaExtension, MangaStatus,
};
use std::sync::OnceLock;
use wit_types::{
    Chapter, ChapterInfo, ChapterList, MangaInfo, MangaList, MangaListItem, Page, PreferenceSpec,
};

kani_shared::guest_alloc!();

pub struct MangapillGen {
    base_url: String,
}

impl Default for MangapillGen {
    fn default() -> Self {
        Self::new()
    }
}

impl MangapillGen {
    pub fn new() -> Self {
        Self {
            base_url: "https://mangapill.com".to_string(),
        }
    }

    pub fn metadata() -> ExtensionMetadata {
        ExtensionMetadata {
            id: "mangapill-gen".to_string(),
            name: "Mangapill".to_string(),
            version: ext_version!("0.1.0"),
            base_url: "https://mangapill.com".to_string(),
            language: "multi".to_string(),
            nsfw: false,
            unrestricted_http: false,
            mihon_source_id: None,
            rate_limit: None,
            ..Default::default()
        }
    }
}

impl MangaExtension for MangapillGen {
    fn name(&self) -> &str {
        "Mangapill"
    }

    fn get_popular_manga(
        &self,
        page: i32,
        page_size: i32,
        filters: &[ActiveFilter],
    ) -> ExtensionResult<MangaList> {
        if filters.is_empty() {
            return Ok(MangaList {
                manga: vec![],
                has_next_page: false,
                total_pages: None,
            });
        }
        self.search_manga("", page, page_size, filters)
    }

    fn search_manga(
        &self,
        query: &str,
        page: i32,
        page_size: i32,
        filters: &[ActiveFilter],
    ) -> ExtensionResult<MangaList> {
        const BP: &[u8] = &[
            0x00, 0x11, 0x2e, 0x67, 0x72, 0x69, 0x64, 0x2e, 0x67, 0x61, 0x70, 0x2d, 0x33, 0x20,
            0x3e, 0x20, 0x64, 0x69, 0x76, 0x03, 0x09, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x5f, 0x75,
            0x72, 0x6c, 0x25, 0x04, 0x24, 0x73, 0x72, 0x63, 0x26, 0x09, 0x0d, 0x00, 0x03, 0x69,
            0x6d, 0x67, 0x08, 0x64, 0x61, 0x74, 0x61, 0x2d, 0x73, 0x72, 0x63, 0x09, 0x0d, 0x00,
            0x03, 0x69, 0x6d, 0x67, 0x03, 0x73, 0x72, 0x63, 0x32, 0x22, 0x03, 0x04, 0x24, 0x73,
            0x72, 0x63, 0x04, 0x68, 0x74, 0x74, 0x70, 0x03, 0x04, 0x24, 0x73, 0x72, 0x63, 0x13,
            0x04, 0x15, 0x68, 0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x6d, 0x61, 0x6e, 0x67,
            0x61, 0x70, 0x69, 0x6c, 0x6c, 0x2e, 0x63, 0x6f, 0x6d, 0x03, 0x04, 0x24, 0x73, 0x72,
            0x63, 0x01, 0x02, 0x69, 0x64, 0x0f, 0x0e, 0x09, 0x0d, 0x00, 0x01, 0x61, 0x04, 0x68,
            0x72, 0x65, 0x66, 0x01, 0x2f, 0x04, 0x00, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x0a,
            0x0d, 0x00, 0x0d, 0x2e, 0x6c, 0x69, 0x6e, 0x65, 0x2d, 0x63, 0x6c, 0x61, 0x6d, 0x70,
            0x2d, 0x32, 0x00, 0x00, 0x00, 0x01, 0x32, 0x04, 0x70, 0x61, 0x67, 0x65, 0x01, 0x01,
        ];
        let mut req = HttpRequest::get(format!("{}/search", self.base_url)).query("q", query);

        for f in filters {
            let (group, action) = f
                .filter_name
                .split_once(':')
                .unwrap_or((&f.filter_name, ""));
            match group {
                "genre" => match &f.state {
                    FilterState::Checkbox(c) if *c => {
                        req = req.query("genre", if action.is_empty() { "true" } else { action });
                    }
                    FilterState::Multiselect(values) => {
                        for v in values {
                            req = req.query("genre", v.as_str());
                        }
                    }
                    FilterState::Selection { value, .. } => {
                        req = req.query("genre", value.as_str())
                    }
                    FilterState::TextInput(s) => req = req.query("genre", s.as_str()),
                    _ => {}
                },
                "status" => match &f.state {
                    FilterState::Checkbox(c) if *c => {
                        req = req.query("status", if action.is_empty() { "true" } else { action });
                    }
                    FilterState::Multiselect(values) => {
                        for v in values {
                            req = req.query("status", v.as_str());
                        }
                    }
                    FilterState::Selection { value, .. } => {
                        req = req.query("status", value.as_str())
                    }
                    FilterState::TextInput(s) => req = req.query("status", s.as_str()),
                    _ => {}
                },
                "type" => match &f.state {
                    FilterState::Checkbox(c) if *c => {
                        req = req.query("type", if action.is_empty() { "true" } else { action });
                    }
                    FilterState::Multiselect(values) => {
                        for v in values {
                            req = req.query("type", v.as_str());
                        }
                    }
                    FilterState::Selection { value, .. } => req = req.query("type", value.as_str()),
                    FilterState::TextInput(s) => req = req.query("type", s.as_str()),
                    _ => {}
                },
                _ => {}
            }
        }
        let rows = extract_raw::paginated_html(page, page_size, req, BP)?;
        let has_next_page = rows.get_scalar_bool("has_next_page");
        let total_pages = None;
        let manga = rows
            .rows_iter()
            .filter_map(|row| {
                Some(MangaListItem {
                    cover_url: row.get_str("/cover_url"),
                    id: row.require_str("/id").ok()?,
                    title: row.require_str("/title").ok()?,
                })
            })
            .collect();
        Ok(MangaList {
            manga,
            has_next_page,
            total_pages,
        })
    }

    fn get_manga_details(&self, manga_id: &str) -> ExtensionResult<MangaInfo> {
        const BP: &[u8] = &[
            0x00, 0x05, 0x3a, 0x72, 0x6f, 0x6f, 0x74, 0x07, 0x07, 0x61, 0x72, 0x74, 0x69, 0x73,
            0x74, 0x73, 0x2d, 0x01, 0x04, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x00,
            0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x2d, 0x01, 0x04, 0x07, 0x55, 0x6e,
            0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x00, 0x09, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x5f, 0x75,
            0x72, 0x6c, 0x09, 0x01, 0x03, 0x69, 0x6d, 0x67, 0x08, 0x64, 0x61, 0x74, 0x61, 0x2d,
            0x73, 0x72, 0x63, 0x01, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
            0x6f, 0x6e, 0x0a, 0x01, 0x09, 0x70, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x2d, 0x73, 0x6d,
            0x01, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x26, 0x27, 0x14, 0x11, 0x0a, 0x01,
            0x3b, 0x64, 0x69, 0x76, 0x2e, 0x67, 0x72, 0x69, 0x64, 0x3a, 0x6e, 0x74, 0x68, 0x2d,
            0x63, 0x68, 0x69, 0x6c, 0x64, 0x28, 0x33, 0x29, 0x20, 0x3e, 0x20, 0x64, 0x69, 0x76,
            0x3a, 0x6e, 0x74, 0x68, 0x2d, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x28, 0x32, 0x29, 0x20,
            0x3e, 0x20, 0x64, 0x69, 0x76, 0x3a, 0x6e, 0x74, 0x68, 0x2d, 0x63, 0x68, 0x69, 0x6c,
            0x64, 0x28, 0x32, 0x29, 0x05, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x69,
            0x6e, 0x67, 0x07, 0x6f, 0x6e, 0x67, 0x6f, 0x69, 0x6e, 0x67, 0x08, 0x66, 0x69, 0x6e,
            0x69, 0x73, 0x68, 0x65, 0x64, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
            0x64, 0x09, 0x6f, 0x6e, 0x20, 0x68, 0x69, 0x61, 0x74, 0x75, 0x73, 0x06, 0x68, 0x69,
            0x61, 0x74, 0x75, 0x73, 0x0c, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e,
            0x75, 0x65, 0x64, 0x09, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x11,
            0x6e, 0x6f, 0x74, 0x20, 0x79, 0x65, 0x74, 0x20, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73,
            0x68, 0x65, 0x64, 0x06, 0x68, 0x69, 0x61, 0x74, 0x75, 0x73, 0x04, 0x07, 0x75, 0x6e,
            0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x00, 0x04, 0x74, 0x61, 0x67, 0x73, 0x34, 0x2c, 0x28,
            0x0c, 0x00, 0x12, 0x64, 0x69, 0x76, 0x2e, 0x6d, 0x62, 0x2d, 0x33, 0x20, 0x61, 0x2e,
            0x74, 0x65, 0x78, 0x74, 0x2d, 0x73, 0x6d, 0x11, 0x0a, 0x03, 0x05, 0x24, 0x69, 0x74,
            0x65, 0x6d, 0x15, 0x03, 0x05, 0x24, 0x69, 0x74, 0x65, 0x6d, 0x05, 0x5b, 0x5e, 0x5c,
            0x73, 0x5d, 0x02, 0x2c, 0x20, 0x01, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x0a, 0x01,
            0x0c, 0x68, 0x31, 0x2e, 0x66, 0x6f, 0x6e, 0x74, 0x2d, 0x62, 0x6f, 0x6c, 0x64, 0x00,
            0x00, 0x00, 0x00,
        ];
        let req = HttpRequest::get(format!("{}/manga/{}", self.base_url, manga_id));
        let _doc = req.send_html()?;
        let rows = extract_raw::html(Some(_doc.handle()), BP)?;
        let row = rows
            .rows_get(0)
            .map_err(|_| kani_shared::ExtensionError::parse("no details row".into()))?;
        let status = match row.get_str("/status").as_deref() {
            Some("ongoing") => MangaStatus::Ongoing,
            Some("completed") => MangaStatus::Completed,
            Some("hiatus") => MangaStatus::Hiatus,
            Some("cancelled") => MangaStatus::Cancelled,
            _ => MangaStatus::Unknown,
        };
        Ok(MangaInfo {
            artists: row.get_array_of_strings("/artists"),
            authors: row.get_array_of_strings("/authors"),
            cover_url: row.get_str("/cover_url"),
            description: row.get_str("/description"),
            id: manga_id.to_string(),
            status,
            tags: row.get_array_of_strings("/tags"),
            title: row.require_str("/title")?,
        })
    }

    fn get_chapter_list(
        &self,
        manga_id: &str,
        _page: i32,
        _page_size: Option<i32>,
        _sort: Option<String>,
    ) -> ExtensionResult<ChapterList> {
        const BP: &[u8] = &[
            0x00, 0x11, 0x64, 0x69, 0x76, 0x2e, 0x67, 0x72, 0x69, 0x64, 0x20, 0x61, 0x2e, 0x62,
            0x6f, 0x72, 0x64, 0x65, 0x72, 0x07, 0x0d, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x75, 0x70,
            0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x06, 0x01, 0x02, 0x69, 0x64, 0x0f, 0x0e, 0x09,
            0x00, 0x04, 0x68, 0x72, 0x65, 0x66, 0x01, 0x2f, 0x04, 0x00, 0x08, 0x6c, 0x61, 0x6e,
            0x67, 0x75, 0x61, 0x67, 0x65, 0x04, 0x02, 0x65, 0x6e, 0x00, 0x06, 0x6e, 0x75, 0x6d,
            0x62, 0x65, 0x72, 0x26, 0x17, 0x0f, 0x0e, 0x11, 0x0a, 0x00, 0x01, 0x20, 0x01, 0x05,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x09, 0x73, 0x63, 0x61, 0x6e,
            0x6c, 0x61, 0x74, 0x6f, 0x72, 0x06, 0x01, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x06,
            0x01, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x06, 0x01, 0x00, 0x00, 0x00,
        ];
        let req = HttpRequest::get(format!("{}/manga/{}", self.base_url, manga_id));
        let _doc = req.send_html()?;
        let rows = extract_raw::html(Some(_doc.handle()), BP)?;
        let count = rows.rows_len();
        let chapters = (0..count)
            .filter_map(|i| {
                let row = rows.rows_get(i).ok()?;
                Some(ChapterInfo {
                    date_uploaded: row.get_i64("/date_uploaded"),
                    id: row.require_str("/id").ok()?,
                    language: row.get_str("/language").unwrap_or_else(|| "en".to_string()),
                    page_count: None,
                    number: row.get_f64("/number").unwrap_or(0.0),
                    scanlator: row.get_str("/scanlator"),
                    title: row.get_str("/title"),
                    volume: row.get_i64("/volume").map(|v| v as i32),
                })
            })
            .collect();
        let has_next_page = false;
        let total_pages = None;
        Ok(ChapterList {
            chapters,
            has_next_page,
            total_pages,
        })
    }

    fn get_pages(&self, _manga_id: &str, chapter_id: &str) -> ExtensionResult<Chapter> {
        const BP: &[u8] = &[
            0x00, 0x0b, 0x69, 0x6d, 0x67, 0x2e, 0x6a, 0x73, 0x2d, 0x70, 0x61, 0x67, 0x65, 0x02,
            0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x31, 0x00, 0x03, 0x75, 0x72, 0x6c, 0x09, 0x00,
            0x08, 0x64, 0x61, 0x74, 0x61, 0x2d, 0x73, 0x72, 0x63, 0x00, 0x00, 0x00, 0x00,
        ];
        let req = HttpRequest::get(format!("{}/chapters/{}", self.base_url, chapter_id));
        let _doc = req.send_html()?;
        let rows = extract_raw::html(Some(_doc.handle()), BP)?;
        let count = rows.rows_len();
        Ok(Chapter {
            pages: (0..count)
                .filter_map(|i| {
                    let row = rows.rows_get(i).ok()?;
                    Some(Page {
                        index: row.get_i64("/index").unwrap_or(i as i64) as i32,
                        url: row.require_str("/url").ok()?,
                        transform: None,
                    })
                })
                .collect(),
        })
    }

    fn get_chapter_sort_list(&self) -> ExtensionResult<Vec<wit_types::SortOption>> {
        Ok(vec![])
    }

    fn get_filter_list(&self) -> ExtensionResult<wit_types::FilterList> {
        Ok(filter_list! {
            "genre:Action", "Action", Checkbox;
            "genre:Adventure", "Adventure", Checkbox;
            "genre:Cars", "Cars", Checkbox;
            "genre:Comedy", "Comedy", Checkbox;
            "genre:Dementia", "Dementia", Checkbox;
            "genre:Demons", "Demons", Checkbox;
            "genre:Doujinshi", "Doujinshi", Checkbox;
            "genre:Drama", "Drama", Checkbox;
            "genre:Ecchi", "Ecchi", Checkbox;
            "genre:Fantasy", "Fantasy", Checkbox;
            "genre:Game", "Game", Checkbox;
            "genre:Gender Bender", "Gender Bender", Checkbox;
            "genre:Harem", "Harem", Checkbox;
            "genre:Historical", "Historical", Checkbox;
            "genre:Horror", "Horror", Checkbox;
            "genre:Isekai", "Isekai", Checkbox;
            "genre:Josei", "Josei", Checkbox;
            "genre:Kids", "Kids", Checkbox;
            "genre:Magic", "Magic", Checkbox;
            "genre:Martial Arts", "Martial Arts", Checkbox;
            "genre:Mecha", "Mecha", Checkbox;
            "genre:Military", "Military", Checkbox;
            "genre:Music", "Music", Checkbox;
            "genre:Mystery", "Mystery", Checkbox;
            "genre:Parody", "Parody", Checkbox;
            "genre:Police", "Police", Checkbox;
            "genre:Psychological", "Psychological", Checkbox;
            "genre:Romance", "Romance", Checkbox;
            "genre:Samurai", "Samurai", Checkbox;
            "genre:School", "School", Checkbox;
            "genre:Sci-Fi", "Sci-Fi", Checkbox;
            "genre:Seinen", "Seinen", Checkbox;
            "genre:Shoujo", "Shoujo", Checkbox;
            "genre:Shoujo Ai", "Shoujo Ai", Checkbox;
            "genre:Shounen", "Shounen", Checkbox;
            "genre:Shounen Ai", "Shounen Ai", Checkbox;
            "genre:Slice of Life", "Slice of Life", Checkbox;
            "genre:Space", "Space", Checkbox;
            "genre:Sports", "Sports", Checkbox;
            "genre:Super Power", "Super Power", Checkbox;
            "genre:Supernatural", "Supernatural", Checkbox;
            "genre:Thriller", "Thriller", Checkbox;
            "genre:Tragedy", "Tragedy", Checkbox;
            "genre:Vampire", "Vampire", Checkbox;
            "genre:Yaoi", "Yaoi", Checkbox;
            "genre:Yuri", "Yuri", Checkbox;
            "type", "Type", Select, [("All", ""), ("Manga", "manga"), ("Manhua", "manhua"), ("Novel", "novel"), ("One-Shot", "one-shot"), ("Doujinshi", "doujinshi"), ("OEL", "oel")], default: ("All", "");
            "status", "Status", Select, [("All", ""), ("Ongoing", "publishing"), ("Completed", "finished"), ("On Hiatus", "on+hiatus"), ("Discontinued", "discontinued"), ("Not Yet Published", "not+yet+published")], default: ("All", "")
        })
    }

    fn get_preferences(&self) -> ExtensionResult<Vec<PreferenceSpec>> {
        Ok(vec![])
    }
}

impl Guest for MangapillGen {
    fn get_metadata() -> Result<String, wit_types::ExtensionError> {
        Ok(
            kani_shared::serde_json::to_string(&MangapillGen::metadata())
                .expect("ExtensionMetadata serializes to JSON"),
        )
    }

    fn get_popular_manga(
        page: i32,
        page_size: i32,
        filters: Vec<wit_types::ActiveFilter>,
    ) -> Result<MangaList, wit_types::ExtensionError> {
        let shared = to_shared_filters(filters);
        get_extension()
            .get_popular_manga(page, page_size, &shared)
            .map_err(|e| e.into_wit())
    }

    fn search_manga(
        query: String,
        page: i32,
        page_size: i32,
        filters: Vec<wit_types::ActiveFilter>,
    ) -> Result<MangaList, wit_types::ExtensionError> {
        let shared = to_shared_filters(filters);
        get_extension()
            .search_manga(&query, page, page_size, &shared)
            .map_err(|e| e.into_wit())
    }

    fn get_filter_list() -> Result<wit_types::FilterList, wit_types::ExtensionError> {
        get_extension().get_filter_list().map_err(|e| e.into_wit())
    }

    fn get_fetched_option_sets() -> Result<String, wit_types::ExtensionError> {
        get_extension()
            .get_fetched_option_sets()
            .map_err(|e| e.into_wit())
    }

    fn get_manga_details(manga_id: String) -> Result<MangaInfo, wit_types::ExtensionError> {
        get_extension()
            .get_manga_details(&manga_id)
            .map_err(|e| e.into_wit())
    }

    fn get_chapter_list(
        manga_id: String,
        page: i32,
        page_size: Option<i32>,
        sort: Option<String>,
    ) -> Result<ChapterList, wit_types::ExtensionError> {
        get_extension()
            .get_chapter_list(&manga_id, page, page_size, sort)
            .map_err(|e| e.into_wit())
    }
    async fn get_chapter_list_stream(
        manga_id: String,
        sort: Option<String>,
    ) -> kani_shared::StreamReader<Result<ChapterInfo, wit_types::ExtensionError>> {
        kani_shared::bridge_chapter_list_stream(get_extension(), manga_id, sort)
    }

    fn get_chapter_sort_list() -> Result<Vec<wit_types::SortOption>, wit_types::ExtensionError> {
        get_extension()
            .get_chapter_sort_list()
            .map_err(|e| e.into_wit())
    }

    fn get_pages(
        manga_id: String,
        chapter_id: String,
    ) -> Result<Chapter, wit_types::ExtensionError> {
        get_extension()
            .get_pages(&manga_id, &chapter_id)
            .map_err(|e| e.into_wit())
    }

    fn get_preferences() -> Result<Vec<PreferenceSpec>, wit_types::ExtensionError> {
        get_extension().get_preferences().map_err(|e| e.into_wit())
    }

    fn get_url(manga_id: String) -> Result<String, wit_types::ExtensionError> {
        get_extension().get_url(&manga_id).map_err(|e| e.into_wit())
    }
}

static EXTENSION: OnceLock<MangapillGen> = OnceLock::new();

fn get_extension() -> &'static MangapillGen {
    EXTENSION.get_or_init(MangapillGen::new)
}

bindings::export!(MangapillGen);
